services:
  - type: web
    name: pjm-forecast-web
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pjm-forecast-db
          property: connectionString
      - key: PJM_7DAY_URL
        sync: false
      - key: AREA_FILTER
        value: RTO_COMBINED
      - key: RETENTION_DAYS
        value: "7"

        

  - type: cron
    name: pjm-forecast-ingest
    env: docker
    schedule: "*/30 * * * *"
    dockerfilePath: Dockerfile.ingest
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pjm-forecast-db
          property: connectionString
      - key: PJM_7DAY_URL
        sync: false
      - key: AREA_FILTER
        value: RTO_COMBINED
      - key: RETENTION_DAYS
        value: "7"

        

databases:
  - name: pjm-forecast-db
    plan: basic-256mb





